

- name: mkdir daemon.sh directory in remote server
  shell: test -d /tmp/idelpig || mkdir -p /tmp/idlepig/

- name: copy install_docker.sh to remote server
  copy: src=install_docker.sh dest=/tmp/idlepig/install_docker.sh

- name: config docker images address in aliyun
  shell: sudo sh /tmp/idlepig/install_docker.sh




